miniProject4BGomez/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    #path("about/", views.AboutView.as_view(), name="about"),
    #path("contact/", views.ContactView.as_view(), name="contact"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime
from django.db import models
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = datetime.timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


#class AboutView(generic.AboutView):
    #template_name = "polls/about.html"


#class ContactView(generic.ContactView):
    #template_name = "polls/contact.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

polls/templates/polls/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

polls/templates/polls/detail.html
<head>
    <meta charset="utf-8" />
    <title>Polls</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div id="details-page">
        <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1 id="details-title">{{ question.question_text }}</h1></legend>
            {% if error_message %}
                <div class="alert alert-danger" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <div class="field-item">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                </div>
            {% endfor %}
        </fieldset>
        <input id="input-button" type="submit" value="Vote">
        </form>
    </div>
    <div>
        <a href="{% url 'polls:index' %}">
            <button class="toIndex-button">Home</button>
        </a>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

polls/templates/polls/details.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<head>
    <meta charset="utf-8" />
    <title>Polls</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <!link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="myWrapper"><h1 id="index-title">Polls</h1></div>
    {% if latest_question_list %}
        <div class="myWrapper">
            <ul class="myUL">
            {% for question in latest_question_list %}
               <div class="list-items"><li class="myListItems"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li></div>
            {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <div id="index-grid">
        <div id="grid-item1">
            <a href="">About</a>
        </div>
        <div id="grid-item2">
            <a href="">Contact</a>
        </div>
    </div>
</body>
<!script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

polls/templates/polls/results.html
<head>
    <meta charset="utf-8" />
    <title>{{ question.question_text }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div>
        <h1 id="results-title">{{ question.question_text }}</h1>
    </div>
    <div>
        <ul>
        {% for choice in question.choice_set.all %}
            <div class="list-items"><li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li></div>
        {% endfor %}
        </ul>
    </div>
    <div id="vote-again">
        <a href="{% url 'polls:detail' question.id %}">
            Vote again?
        </a>
    </div>
    <div>
        <a href="{% url 'polls:index' %}">
            <button class="toIndex-button">Home</button>
        </a>
    </div>
</body>